---
- hosts: loadbalancers
  become: true
  vars:
    certbot_domain: "home.adamatyi.com"
    certbot_email: "atyiadam@gmail.com"
    cloudflare_token: "{{ lookup('env', 'CLOUDFLARE_TOKEN') }}"
    cert_dir: "/etc/haproxy/certs"
    combined_cert: "{{ cert_dir }}/combinedcert.pem"
    lb_service_account: "haproxy"
  roles:
    - certbot-install-and-configure

- hosts: loadbalancers
  become: true
  vars:
    cert_dir: "/etc/haproxy/certs"
    combined_cert: "{{ cert_dir }}/combinedcert.pem"
    haproxy_https_backends:
      #===============================================================================
      # Proxmox
      #===============================================================================
      - name: proxmox
        domain: proxmox.home.adamatyi.com
        servers:
          - name: proxmox_pve_01
            address: 10.10.20.10
            port: 8006
    haproxy_http_backends:
      #===============================================================================
      # Synology
      #===============================================================================
      - name: qbittorrent
        domain: qbittorrent.home.adamatyi.com
        server_prefix: qbittorrent
        server_ip_prefix: 10.10.30
        server_start: 2
        server_end: 2
        port: 8080
      #===============================================================================
      # k8s-01.prod
      #===============================================================================
      - name: k8s-01-prod-argocd
        domain: argocd-k8s-01-prod.home.adamatyi.com
        server_prefix: argocd
        server_ip_prefix: 10.10.30
        server_start: 152
        server_end: 159
        port: 30080
      - name: jellyfin
        domain: jellyfin.home.adamatyi.com
        server_prefix: jellyfin
        server_ip_prefix: 10.10.30
        server_start: 152
        server_end: 159
        port: 30081
      - name: prowlarr
        domain: prowlarr.home.adamatyi.com
        server_prefix: prowlarr
        server_ip_prefix: 10.10.30
        server_start: 152
        server_end: 159
        port: 30083
      - name: radarr
        domain: radarr.home.adamatyi.com
        server_prefix: radarr
        server_ip_prefix: 10.10.30
        server_start: 152
        server_end: 159
        port: 30082
      - name: sonarr
        domain: sonarr.home.adamatyi.com
        server_prefix: sonarr
        server_ip_prefix: 10.10.30
        server_start: 152
        server_end: 159
        port: 30084
      - name: k8s-01-prod-longhorn
        domain: longhorn-k8s-01-prod.home.adamatyi.com
        server_prefix: longhorn
        server_ip_prefix: 10.10.30
        server_start: 152
        server_end: 159
        port: 30085
  roles:
    - haproxy-install-and-configure

