---
- name: Include common tasks
  include_tasks: common.yml

- name: Ensure nfs-common is installed
  apt:
    name: nfs-common
    state: present

- name: Install RKE2 agent
  shell: INSTALL_RKE2_TYPE="agent" INSTALL_RKE2_VERSION={{ rke2_version }} INSTALL_RKE2_CHANNEL={{ rke2_channel }} sh /tmp/rke2-install.sh
  args:
    creates: /usr/local/bin/rke2

 # Longhorn related tasks
- name: Ensure iscsi_tcp kernel module is loaded
  modprobe:
    name: iscsi_tcp
    state: present

- name: Ensure iscsi_tcp is loaded on boot
  lineinfile:
    path: /etc/modules-load.d/iscsi_tcp.conf
    line: "iscsi_tcp"
    create: yes
    state: present

- name: Stop and disable multipathd service
  systemd:
    name: multipathd
    state: stopped
    enabled: no
    daemon_reload: yes

- name: Ensure multipathd is fully terminated
  command: "pkill -9 multipathd || true"
  register: pkill_result
  changed_when: pkill_result.rc == 0
  failed_when: false  # Don't fail if process is already gone

- name: Ensure dm_crypt kernel module is loaded
  modprobe:
    name: dm_crypt
    state: present

- name: Ensure dm_crypt is loaded on boot
  lineinfile:
    path: /etc/modules-load.d/dm_crypt.conf
    line: "dm_crypt"
    create: yes
    state: present

- name: Ensure Longhorn storage directory exists
  file:
    path: /var/lib/longhorn
    state: directory
    mode: '0755'
  when: rke2_type == 'agent'

- name: Enable and start RKE2 agent service
  systemd:
    name: rke2-agent
    enabled: yes
    state: started
