---
# Ensure UFW is installed and running
- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny

# Server-specific rules
- name: Configure UFW rules for RKE2 server nodes
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    src: "{{ item.src }}"
  loop:
    # Kubernetes API - Accept from agent nodes
    - port: '6443'
      proto: tcp
      src: "{{ rke2_cluster_cidr }}"
    
    # RKE2 supervisor API - Accept from agent nodes
    - port: '9345'
      proto: tcp
      src: "{{ rke2_cluster_cidr }}"
    
    # etcd client port - Accept from server nodes only
    - port: '2379'
      proto: tcp
      src: "{{ rke2_server_cidr }}"
    
    # etcd peer port - Accept from server nodes only
    - port: '2380'
      proto: tcp
      src: "{{ rke2_server_cidr }}"
    
    # etcd metrics port - Accept from server nodes only
    - port: '2381'
      proto: tcp
      src: "{{ rke2_server_cidr }}"
  when: "group_names | select('match', '.*_servers$') | list | length > 0"
  notify: reload ufw

# Common rules for both server and agent nodes
- name: Configure UFW common rules for all RKE2 nodes
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    src: "{{ item.src }}"
  loop:
    # kubelet metrics - Accept from all RKE2 nodes
    - port: '10250'
      proto: tcp
      src: "{{ rke2_cluster_cidr }}"
  notify: reload ufw

# NodePort range requires special handling in UFW
- name: Configure NodePort range for all RKE2 nodes
  ufw:
    rule: allow
    port: "30000:32767"
    proto: tcp
    src: "{{ rke2_cluster_cidr }}"
  notify: reload ufw
