---
- name: Initialize keepalived on k8s-01 servers
  hosts: k8s_01_servers
  become: yes
  vars:
    # Keepalived settings
    keepalived_vip: "10.10.30.155"
    keepalived_interface: "eth0"
    keepalived_router_id: 50
    keepalived_temp_pass: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters,digits') }}"

  pre_tasks:
    - name: Set keepalived auth password
      set_fact:
        keepalived_auth_pass: "{{ keepalived_temp_pass }}"
      run_once: true

  roles:
    - rke2-server-keepalived
