---
# Ensure UFW is installed and running
- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny

# Configure Cilium-specific rules

# ICMP for health checks
# - name: Configure ICMP for Cilium CNI
#   command: "ufw allow from {{ rke2_cluster_cidr }} proto icmp"
#   changed_when: false
#   notify: reload ufw
  
- name: Configure UFW rules for Cilium CNI
  ufw:
    rule: allow
    src: "{{ item.src }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto }}"
  loop:
    # Cilium health checks
    - port: '4240'
      proto: tcp
      src: "{{ rke2_cluster_cidr }}"
    
    # Cilium VXLAN overlay
    - port: '8472'
      proto: udp
      src: "{{ rke2_cluster_cidr }}"
  notify: reload ufw

