---
# Ensure UFW is installed and running
- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny

- name: Allow DNS traffic 
  ufw:
    rule: allow
    port: "53"
  notify: reload ufw

- name: Allow webserver traffic
  ufw:
    rule: allow
    proto: tcp
    port: "8082"
  notify: reload ufw
