---
- name: Install keepalived
  apt:
    name: keepalived
    state: present
    update_cache: yes

- name: Enable and start keepalived
  systemd:
    name: keepalived
    state: started
    enabled: yes

- name: Create keepalived config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart keepalived

